//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_santiagoEntities : DbContext
    {
        public bd_santiagoEntities()
            : base("name=bd_santiagoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<moneda> moneda { get; set; }
        public DbSet<presupuesto_repuesto> presupesto_repuesto { get; set; }
        public DbSet<presupuesto> presupuesto { get; set; }
        public DbSet<presupuesto_comercial> presupuesto_comercial { get; set; }
        public DbSet<presupuesto_comercial_condicion_venta> presupuesto_comercial_condicion_venta { get; set; }
        public DbSet<presupuesto_comercial_detalle> presupuesto_comercial_detalle { get; set; }
        public DbSet<presupuesto_comercial_resumen> presupuesto_comercial_resumen { get; set; }
        public DbSet<presupuesto_control_orden_trabajo> presupuesto_control_orden_trabajo { get; set; }
        public DbSet<presupuesto_orden_trabajo> presupuesto_orden_trabajo { get; set; }
        public DbSet<presupuesto_repuesto_desgloce> presupuesto_repuesto_desgloce { get; set; }
        public DbSet<presupuesto_trabajo_resumen> presupuesto_trabajo_resumen { get; set; }
        public DbSet<presupuesto_trabajo_resumen_comercial_detalle> presupuesto_trabajo_resumen_comercial_detalle { get; set; }
        public DbSet<presupuesto_trabajo_resumen_comision_desgloce> presupuesto_trabajo_resumen_comision_desgloce { get; set; }
        public DbSet<presupuesto_trabajo_resumen_comision_detalle> presupuesto_trabajo_resumen_comision_detalle { get; set; }
        public DbSet<presupuesto_trabajo_resumen_mo_detalle> presupuesto_trabajo_resumen_mo_detalle { get; set; }
        public DbSet<presupuesto_trabajo_terceros> presupuesto_trabajo_terceros { get; set; }
        public DbSet<presupuesto_trabajo_terceros_desgloce> presupuesto_trabajo_terceros_desgloce { get; set; }
        public DbSet<repuesto> repuesto { get; set; }
        public DbSet<tipo_esfuerzo> tipo_esfuerzo { get; set; }
        public DbSet<tipo_moneda> tipo_moneda { get; set; }
        public DbSet<valor_esfuerzo> valor_esfuerzo { get; set; }
    }
}
