//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class moneda
    {
        public moneda()
        {
            this.presupuesto = new HashSet<presupuesto>();
        }
    
        public int PK_valor_moneda_id { get; set; }
        public decimal Valor_moneda { get; set; }
        public bool Estado { get; set; }
        public sbyte Tipo_moneda { get; set; }
    
        public virtual tipo_moneda tipo_moneda1 { get; set; }
        public virtual ICollection<presupuesto> presupuesto { get; set; }
    }
}
