//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_trabajo_resumen_comision_detalle
    {
        public presupuesto_trabajo_resumen_comision_detalle()
        {
            this.presupuesto_trabajo_resumen_comision_desgloce = new HashSet<presupuesto_trabajo_resumen_comision_desgloce>();
        }
    
        public int PK_ppto_trabajo_resumen_comision_detalle_id { get; set; }
        public int Presupuesto_Trabajo_Resumen { get; set; }
        public Nullable<decimal> Valor_Venta { get; set; }
        public Nullable<decimal> Valor_Margen_Venta { get; set; }
        public Nullable<int> Cantidad_Fletes { get; set; }
        public Nullable<decimal> Total_Fletes { get; set; }
    
        public virtual presupuesto_trabajo_resumen presupuesto_trabajo_resumen1 { get; set; }
        public virtual ICollection<presupuesto_trabajo_resumen_comision_desgloce> presupuesto_trabajo_resumen_comision_desgloce { get; set; }
    }
}
