//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_control_orden_trabajo
    {
        public int PK_Presupuesto_Control_OC_id { get; set; }
        public int Presupuesto_Orden_Trabajo { get; set; }
        public Nullable<System.DateTime> Fecha_Termino_Tecnico { get; set; }
        public Nullable<int> Numero_Guia { get; set; }
        public string Tecnico { get; set; }
        public Nullable<System.DateTime> Fecha_Termino_Supervisor { get; set; }
        public string Supervisor { get; set; }
        public Nullable<int> Numero_Ventas { get; set; }
        public Nullable<System.DateTime> Fecha_Termino_Venta { get; set; }
    
        public virtual presupuesto_orden_trabajo presupuesto_orden_trabajo1 { get; set; }
    }
}
