//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_repuesto_desgloce
    {
        public int PK_ppto_repuesto_desgloce_id { get; set; }
        public int Presupuesto_Repuesto { get; set; }
        public decimal Valor_Repuesto { get; set; }
        public decimal Valor_Mano_Obra { get; set; }
        public decimal Valor_Comision_1 { get; set; }
        public decimal Valor_Comision_2 { get; set; }
    
        public virtual presupuesto_repuesto presupesto_repuesto { get; set; }
    }
}
