//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_comercial
    {
        public presupuesto_comercial()
        {
            this.presupuesto_comercial_detalle = new HashSet<presupuesto_comercial_detalle>();
        }
    
        public int Presupuesto_Comercial_id { get; set; }
        public int Presupuesto { get; set; }
        public Nullable<int> Obra { get; set; }
        public Nullable<System.DateTime> Fecha_Aprobacion { get; set; }
        public Nullable<int> Numero_Ascensor { get; set; }
        public string Descripcion { get; set; }
        public string Nombre_Aprobador { get; set; }
        public Nullable<int> Telefono_Contacto { get; set; }
        public string Direccion { get; set; }
    
        public virtual presupuesto presupuesto1 { get; set; }
        public virtual ICollection<presupuesto_comercial_detalle> presupuesto_comercial_detalle { get; set; }
    }
}
