//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_trabajo_terceros_desgloce
    {
        public int PK_ppto_trabajo_terceros_desgloce_id { get; set; }
        public int Presupuesto_Trabajo_Tercero { get; set; }
        public Nullable<decimal> Valor_Trabajo_Taller { get; set; }
        public Nullable<decimal> Valor_Mano_Obra { get; set; }
        public Nullable<decimal> Valor_Comision_1 { get; set; }
        public Nullable<decimal> Valor_Comision_2 { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual presupuesto_trabajo_terceros presupuesto_trabajo_terceros { get; set; }
    }
}
