//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_trabajo_terceros
    {
        public presupuesto_trabajo_terceros()
        {
            this.presupuesto_trabajo_terceros_desgloce = new HashSet<presupuesto_trabajo_terceros_desgloce>();
        }
    
        public int PK_ppto_trabajo_terceros_id { get; set; }
        public int Presupuesto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Valor { get; set; }
    
        public virtual presupuesto presupuesto1 { get; set; }
        public virtual ICollection<presupuesto_trabajo_terceros_desgloce> presupuesto_trabajo_terceros_desgloce { get; set; }
    }
}
