//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_comercial_resumen
    {
        public int PK_Presupuesto_Comercial_Resumen_id { get; set; }
        public int Presupuesto_Comercial_Detalle { get; set; }
        public Nullable<decimal> Valor_Mano_Obra { get; set; }
        public Nullable<decimal> Valor_Repuesto { get; set; }
        public Nullable<decimal> Valor_Terceros { get; set; }
        public Nullable<decimal> Valor_Fletes { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
    
        public virtual presupuesto_comercial_detalle presupuesto_comercial_detalle1 { get; set; }
    }
}
