//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_orden_trabajo
    {
        public presupuesto_orden_trabajo()
        {
            this.presupuesto_control_orden_trabajo = new HashSet<presupuesto_control_orden_trabajo>();
        }
    
        public int PK_Presupuesto_Orden_Trabajo_id { get; set; }
        public int Presupuesto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Obra { get; set; }
        public Nullable<System.DateTime> Fecha_Aprobacion { get; set; }
        public string Ascensor { get; set; }
        public string Tecnico_Emisor { get; set; }
        public string Supervisor { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> Aprobacion { get; set; }
        public Nullable<int> Telefono_Contacto { get; set; }
        public string Descripcion { get; set; }
        public string Descripcion_Terceros { get; set; }
    
        public virtual presupuesto presupuesto1 { get; set; }
        public virtual ICollection<presupuesto_control_orden_trabajo> presupuesto_control_orden_trabajo { get; set; }
    }
}
