//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_trabajo_resumen_comercial_detalle
    {
        public int PK_ppto_trabajo_resumen_comercial_detalle_id { get; set; }
        public int Presupuesto_Trabajo_Resumen { get; set; }
        public Nullable<decimal> Valor_Mano_Obra { get; set; }
        public Nullable<decimal> Valor_Repuestos { get; set; }
        public Nullable<decimal> Valor_Terceros { get; set; }
        public Nullable<decimal> Valor_Fletes { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<int> Porcentaje_Comision_Vendedor { get; set; }
        public Nullable<decimal> Valor_Comision_Vendedor { get; set; }
        public Nullable<int> Porcentaje_Comision_Otro_Vendedor { get; set; }
        public Nullable<decimal> Valor_Comision_Otro_Vendedor { get; set; }
    
        public virtual presupuesto_trabajo_resumen presupuesto_trabajo_resumen1 { get; set; }
    }
}
