//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_trabajo_resumen_mo_detalle
    {
        public int PK_ppto_trabajo_resumen_mo_detalle_id { get; set; }
        public int Presupuesto_Trabajo_Resumen { get; set; }
        public Nullable<decimal> Horas_Parejas { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Recargo_HH_EE { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual presupuesto_trabajo_resumen presupuesto_trabajo_resumen1 { get; set; }
    }
}
