//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class repuesto
    {
        public repuesto()
        {
            this.presupesto_repuesto = new HashSet<presupuesto_repuesto>();
        }
    
        public int PK_repuesto_id { get; set; }
        public string Codigo_repuesto { get; set; }
        public string Nombre_Articulo { get; set; }
        public string Marca_Articulo { get; set; }
        public int Unidad { get; set; }
        public int Precio_Compra { get; set; }
        public Nullable<int> Precio_Venta { get; set; }
    
        public virtual ICollection<presupuesto_repuesto> presupesto_repuesto { get; set; }
    }
}
