//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_esfuerzo
    {
        public sbyte PK_Tipo_esfuerzo_id { get; set; }
        public string Descripcion_esfuerzo { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
