//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_moneda
    {
        public tipo_moneda()
        {
            this.moneda = new HashSet<moneda>();
        }
    
        public sbyte PK_Tipo_moneda_id { get; set; }
        public string Descripcion { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<moneda> moneda { get; set; }
    }
}
