//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class valor_esfuerzo
    {
        public valor_esfuerzo()
        {
            this.presupuesto = new HashSet<presupuesto>();
            this.presupuesto1 = new HashSet<presupuesto>();
        }
    
        public sbyte PK_Valor_esfuerzo_id { get; set; }
        public string Descripcion_Esfuerzo { get; set; }
        public Nullable<decimal> Valor_Esfuerzo1 { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual ICollection<presupuesto> presupuesto { get; set; }
        public virtual ICollection<presupuesto> presupuesto1 { get; set; }
    }
}
