//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class flete_valor
    {
        public flete_valor()
        {
            this.presupuesto = new HashSet<presupuesto>();
        }
    
        public int idFlete_Valor { get; set; }
        public string Tipo { get; set; }
        public int Valor { get; set; }
    
        public virtual ICollection<presupuesto> presupuesto { get; set; }
    }
}
