//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_santiagoEntities : DbContext
    {
        public bd_santiagoEntities()
            : base("name=bd_santiagoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<flete_valor> flete_valor { get; set; }
        public DbSet<hh_valorizacion> hh_valorizacion { get; set; }
        public DbSet<presupuesto> presupuesto { get; set; }
        public DbSet<presupuesto_comercial> presupuesto_comercial { get; set; }
        public DbSet<presupuesto_comercial_condicion_venta> presupuesto_comercial_condicion_venta { get; set; }
        public DbSet<presupuesto_comercial_detalle> presupuesto_comercial_detalle { get; set; }
        public DbSet<presupuesto_comercial_pago> presupuesto_comercial_pago { get; set; }
        public DbSet<presupuesto_comercial_resumen> presupuesto_comercial_resumen { get; set; }
        public DbSet<presupuesto_orden_trabajo> presupuesto_orden_trabajo { get; set; }
        public DbSet<presupuesto_orden_trabajo_detalle> presupuesto_orden_trabajo_detalle { get; set; }
        public DbSet<presupuesto_tercero_comision> presupuesto_tercero_comision { get; set; }
        public DbSet<presupuesto_tercero_detalle> presupuesto_tercero_detalle { get; set; }
        public DbSet<presupuesto_tercero_flete> presupuesto_tercero_flete { get; set; }
        public DbSet<presupuesto_tercero_flete_detalle> presupuesto_tercero_flete_detalle { get; set; }
        public DbSet<presupuesto_trabajo_resumen> presupuesto_trabajo_resumen { get; set; }
        public DbSet<presupuesto_trabajo_resumen_detalle> presupuesto_trabajo_resumen_detalle { get; set; }
        public DbSet<presupuesto_trabajo_terceros> presupuesto_trabajo_terceros { get; set; }
        public DbSet<repuesto_presupuesto> repuesto_presupuesto { get; set; }
        public DbSet<repuesto_presupuesto_detalle> repuesto_presupuesto_detalle { get; set; }
        public DbSet<repuestos> repuestos { get; set; }
        public DbSet<valor_moneda> valor_moneda { get; set; }
        public DbSet<test> test { get; set; }
    }
}
