//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_comercial_condicion_venta
    {
        public int idpresupuesto_comercial_condicion_venta { get; set; }
        public string porcentaje_cinco { get; set; }
        public string porcentaje_quince { get; set; }
        public string porcentaje_otro { get; set; }
        public Nullable<int> valor_otro { get; set; }
        public string Pago_Completo_Termino_Trabajo { get; set; }
        public string Pago_Incompleto_Termino_TRabajo { get; set; }
        public int Cuotas { get; set; }
        public int Numero_Cuotas { get; set; }
        public string Otro_Descuento { get; set; }
        public string Descripcion_Otro_Descuento { get; set; }
        public string Copia_Presupuesto_Firmado { get; set; }
        public string Orden_Compra { get; set; }
        public string Otro_Medio { get; set; }
        public string Descripcion_Otro_Medio { get; set; }
    }
}
