//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_comercial_pago
    {
        public int idpresupuesto_comercial_pago { get; set; }
        public int Numero_Cuota { get; set; }
        public int Numero_Factura { get; set; }
        public int Valor { get; set; }
        public System.DateTime Mes_Asociado { get; set; }
    }
}
