//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_tercero_flete_detalle
    {
        public int idpresupuesto_tercero_flete_detalle { get; set; }
        public int Valor_Flete { get; set; }
        public int Mano_Obra { get; set; }
        public int Comision1 { get; set; }
        public int Comision2 { get; set; }
        public int Total { get; set; }
    }
}
