//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_comercial_resumen
    {
        public int idpresupuesto_comercial_resumen { get; set; }
        public int Valor_Mano_Obra { get; set; }
        public int Valor_Repuesto { get; set; }
        public int Valor_Terceros { get; set; }
        public int Valor_Fletes { get; set; }
        public int SubTotal { get; set; }
    }
}
