//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_comercial
    {
        public int idpresupuesto_Comercial { get; set; }
        public int Obra { get; set; }
        public System.DateTime Fecha_Aprobacion { get; set; }
        public int Numero_Ascensor { get; set; }
        public string Descripcion { get; set; }
        public string Nombre_Aprobador { get; set; }
        public Nullable<int> Telefono_Contacto { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Numero_presupuesto { get; set; }
    }
}
