//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_tercero_comision
    {
        public int idPresupuesto_Tercero_Comision { get; set; }
        public string Tipo_Comision { get; set; }
        public int Valor_porcentaje { get; set; }
        public int Total_Porcentaje { get; set; }
        public int Total_Neto { get; set; }
    }
}
