//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_orden_trabajo
    {
        public int idpresupuesto_orden_trabajo { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Obra { get; set; }
        public string Fecha_Aprobacion { get; set; }
        public string Ascensor { get; set; }
        public string Tecnico_Emisor { get; set; }
        public string Supervisor { get; set; }
        public string Direccion { get; set; }
        public string Aprobacion { get; set; }
        public Nullable<int> Telefono_Contacto { get; set; }
        public string Descripcion { get; set; }
        public string Descripcion_Terceros { get; set; }
    }
}
