//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto
    {
        public int idPresupuesto { get; set; }
        public System.DateTime Fecha_Emision { get; set; }
        public string Presupuesto_Descripcion { get; set; }
        public int Valor_UF_Referencial { get; set; }
        public int Valor_HH_Referencial { get; set; }
        public int Valor_Flete { get; set; }
        public int idTecnico { get; set; }
        public int idSupervisor { get; set; }
    
        public virtual repuesto_presupuesto repuesto_presupuesto { get; set; }
        public virtual valor_moneda valor_moneda { get; set; }
        public virtual flete_valor flete_valor { get; set; }
        public virtual hh_valorizacion hh_valorizacion { get; set; }
    }
}
