//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_trabajo_resumen_detalle
    {
        public int idPresupuesto_Trabajo_Resumen_Detalle { get; set; }
        public int Horas_Pareja { get; set; }
        public int Sub_Total { get; set; }
        public int Recargo_HHEE { get; set; }
        public int Valor_Recargo { get; set; }
        public int Total { get; set; }
    }
}
