//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_trabajo_resumen
    {
        public int idpresupuesto_trabajo_resumen { get; set; }
        public string Resumen { get; set; }
        public int Sub_Total { get; set; }
        public int Total_Neto_Comisiones { get; set; }
    }
}
