//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class repuestos
    {
        public int idRepuestos { get; set; }
        public int codigo { get; set; }
        public string Nombre_Articulo { get; set; }
        public string Marca { get; set; }
        public string Unidad { get; set; }
        public int Precio_Venta { get; set; }
        public int Precio_Compra { get; set; }
    }
}
