//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class repuesto_presupuesto_detalle
    {
        public int idRepuesto_Presupuesto_Detalle { get; set; }
        public int Valor_MO { get; set; }
        public int Valor_Comision1 { get; set; }
        public int Valor_Comision2 { get; set; }
        public int Total { get; set; }
    
        public virtual repuesto_presupuesto repuesto_presupuesto { get; set; }
    }
}
