//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class repuesto_presupuesto
    {
        public int idRepuestoPresupuesto { get; set; }
        public string Nombre { get; set; }
        public int Cantidad { get; set; }
        public int Codigo { get; set; }
        public string Valor_Unitario { get; set; }
        public decimal Sub_Total { get; set; }
        public int Hora_Par_Hombre { get; set; }
    
        public virtual presupuesto presupuesto { get; set; }
        public virtual repuesto_presupuesto_detalle repuesto_presupuesto_detalle { get; set; }
    }
}
